In [1]:
import pandas as pd
import numpy as np

In [2]:
x1=np.random.randint(low=1,high=20,size=(50,))


x2=np.random.randint(low=1,high=20,size=(50,))

In [3]:
print(x1)
print(x2)

[ 9 11 15  2  9 18  1  6 13  1 16 10  6 13  4 12 16 10  8  2  3  5  9 18 10
 10 16  1 16  8  6  1  3  7 17  7 15  3 18  3  7  7 11 16  7 16  6 11 10 16]
[15  5  5  7  5 15 12  1  3 10 12  4  8 11 11 13  3 16 15 16  2  1 17 17  9
 18 19 15  6  3 13 17  7  4  9 18  7 12 11  3  6  1 10 11  4  5  6 15  3 17]


In [4]:
y=3+2*x1-4*x2+np.random.random((50,))
y

array([-38.14868572,   5.00555619,  13.5466996 , -20.32461757,
         1.9534787 , -20.62477191, -42.08501372,  11.9875843 ,
        17.49426514, -34.43357495, -12.43330488,   7.40626059,
       -16.86003839, -14.98460737, -32.90489474, -24.24831564,
        23.00267859, -40.83586518, -40.7157864 , -56.46503138,
         1.60227864,   9.15358244, -46.70700564, -28.90480127,
       -12.65061187, -48.54461002, -40.33133482, -54.23768519,
        11.58548878,   7.43344402, -36.46727374, -62.346563  ,
       -18.82561823,   1.76880337,   1.33605384, -54.78570104,
         5.5079252 , -38.51362052,  -4.88348631,  -2.68046811,
        -6.69328124,  13.81275888, -14.76554378,  -8.9322301 ,
         1.4986525 ,  15.68093716,  -8.5880229 , -34.14827417,
        11.56469136, -32.64577133])

In [5]:
x=pd.DataFrame({'intercept':np.ones_like(x1),'x1':x1,'x2':x2})

w=np.zeros(x.shape[1])

In [6]:
x

intercept  x1  x2
0           1   9  15
1           1  11   5
2           1  15   5
3           1   2   7
4           1   9   5
5           1  18  15
6           1   1  12
7           1   6   1
8           1  13   3
9           1   1  10
10          1  16  12
11          1  10   4
12          1   6   8
13          1  13  11
14          1   4  11
15          1  12  13
16          1  16   3
17          1  10  16
18          1   8  15
19          1   2  16
20          1   3   2
21          1   5   1
22          1   9  17
23          1  18  17
24          1  10   9
25          1  10  18
26          1  16  19
27          1   1  15
28          1  16   6
29          1   8   3
30          1   6  13
31          1   1  17
32          1   3   7
33          1   7   4
34          1  17   9
35          1   7  18
36          1  15   7
37          1   3  12
38          1  18  11
39          1   3   3
40          1   7   6
41          1   7   1
42          1  11  10
43          1  16  11
44          1   7   4
45          1  16   5
46          1   6   6
47          1  11  15
48          1  10   3
49          1  16  17

In [7]:
w

array([ 0.,  0.,  0.])

In [8]:
def myprediction(features,weights):

    predictions=np.dot(features,weights)
    return(predictions)

In [9]:
myprediction(x,w)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [11]:
def myerror(target,features,weights):
    error=target-myprediction(features,weights)
    return(error)

In [12]:
def mycost(target,features,weights):
    error=myerror(target,features,weights)
    cost=np.dot(error.T,error)
    return(cost)

In [13]:
mycost(y,x,w)

39065.594003764563

In [14]:
def gradient(target,features,weights):
    
    error=myerror(target,features,weights)
    
    gradient=-np.dot(features.T,error)
    
    return(gradient)

In [15]:
gradient(y,x,w)

array([   789.37527182,   5178.5484525 ,  13040.0401356 ])

In [16]:
def my_lr(target,features,learning_rate):
    
    weights=np.zeros(features.shape[1])
    
    for i in np.arange(100000):
        weights -= learning_rate*gradient(target,features,weights)
        weights[0] -=10*learning_rate*gradient(target,features,weights)[0] # if you comment this out , your coefficient estimates will not be as good as sklearn, why?
        if i%100==0:
            print(mycost(target,features,weights),weights)
    return(weights)

In [17]:
my_lr(y,x,0.000001)

38660.2281357 [-0.00859697 -0.00517855 -0.01304004]
19546.2351057 [-0.5114434  -0.19160364 -0.92915697]
13988.9873984 [-0.65100963 -0.05886591 -1.43085393]
10732.4284623 [-0.66930866  0.15780773 -1.76995473]
8328.07886266 [-0.64773156  0.38202503 -2.03402232]
6478.45738535 [-0.61359168  0.59054427 -2.25497301]
5046.63075562 [-0.57600262  0.77772491 -2.44569268]
3937.12383423 [-0.53795905  0.94359178 -2.61240243]
3077.17451434 [-0.50040381  1.08984694 -2.75885347]
2410.54969385 [-0.46359647  1.21855436 -2.88776683]
1893.70033701 [-0.42757331  1.33172124 -3.00134195]
1492.89012843 [-0.3923014   1.4311784  -3.10144888]
1181.9832158 [-0.35772976  1.51855893 -3.18971142]
940.731741488 [-0.32380595  1.59530747 -3.26755134]
753.449332942 [-0.29048115  1.66269802 -3.33621757]
607.983457963 [-0.25771133  1.72185274 -3.39680854]
494.919297511 [-0.22545723  1.77375958 -3.45029077]
406.962975979 [-0.19368401  1.81928823 -3.49751491]
338.463741721 [-0.16236074  1.85920416 -3.53922964]
285.043794059

14.5519712124 [ 2.3668478   2.04463192 -3.94776435]
14.3742669685 [ 2.37651672  2.04417864 -3.94819378]
14.1993540151 [ 2.3861094   2.04372894 -3.94861982]
14.0271885082 [ 2.39562644  2.04328278 -3.9490425 ]
13.8577272922 [ 2.40506844  2.04284014 -3.94946185]
13.6909278894 [ 2.41443599  2.04240098 -3.94987789]
13.5267484894 [ 2.42372968  2.0419653  -3.95029065]
13.3651479384 [ 2.43295009  2.04153304 -3.95070015]
13.2060857293 [ 2.44209779  2.0411042  -3.95110643]
13.0495219908 [ 2.45117337  2.04067873 -3.95150951]
12.8954174784 [ 2.4601774   2.04025662 -3.9519094 ]
12.7437335636 [ 2.46911042  2.03983784 -3.95230615]
12.594432225 [ 2.47797301  2.03942236 -3.95269976]
12.4474760383 [ 2.48676572  2.03901016 -3.95309027]
12.3028281668 [ 2.4954891   2.03860121 -3.9534777 ]
12.1604523527 [ 2.5041437   2.03819548 -3.95386208]
12.0203129078 [ 2.51273006  2.03779295 -3.95424342]
11.8823747042 [ 2.52124872  2.0373936  -3.95462176]
11.7466031658 [ 2.5297002   2.03699739 -3.95499712]
11.6129642598

4.1513515604 [ 3.24481187  2.00347289 -3.98675738]
4.13701512151 [ 3.24755818  2.00334414 -3.98687935]
4.12290387233 [ 3.25028283  2.00321641 -3.98700036]
4.1090142757 [ 3.252986    2.00308969 -3.98712042]
4.09534285 [ 3.25566786  2.00296396 -3.98723953]
4.08188616831 [ 3.25832857  2.00283923 -3.9873577 ]
4.06864085755 [ 3.26096831  2.00271548 -3.98747494]
4.05560359759 [ 3.26358722  2.0025927  -3.98759125]
4.04277112049 [ 3.26618549  2.00247089 -3.98770665]
4.03014020961 [ 3.26876327  2.00235005 -3.98782114]
4.01770769885 [ 3.27132073  2.00223015 -3.98793472]
4.00547047183 [ 3.27385802  2.00211121 -3.98804741]
3.99342546115 [ 3.27637531  2.00199319 -3.98815921]
3.98156964755 [ 3.27887274  2.00187611 -3.98827013]
3.96990005923 [ 3.28135049  2.00175996 -3.98838017]
3.95841377105 [ 3.2838087   2.00164472 -3.98848935]
3.94710790382 [ 3.28624752  2.00153038 -3.98859766]
3.93597962358 [ 3.28866712  2.00141695 -3.98870513]
3.92502614087 [ 3.29106764  2.00130442 -3.98881174]
3.91424471007 [ 3

3.31111624459 [ 3.49496437  1.99174572 -3.99786741]
3.30997780773 [ 3.49573827  1.99170944 -3.99790178]
3.30885725287 [ 3.49650606  1.99167345 -3.99793588]
3.30775429914 [ 3.49726781  1.99163774 -3.99796971]
3.30666867006 [ 3.49802354  1.99160231 -3.99800327]
3.30560009351 [ 3.49877332  1.99156716 -3.99803657]
3.30454830163 [ 3.49951718  1.99153228 -3.99806961]
3.30351303078 [ 3.50025518  1.99149769 -3.99810239]
3.30249402145 [ 3.50098736  1.99146336 -3.99813491]
3.30149101822 [ 3.50171377  1.99142931 -3.99816717]
3.30050376967 [ 3.50243445  1.99139552 -3.99819918]
3.29953202833 [ 3.50314944  1.991362   -3.99823093]
3.29857555063 [ 3.5038588   1.99132875 -3.99826244]
3.29763409681 [ 3.50456257  1.99129576 -3.99829369]
3.29670743088 [ 3.50526079  1.99126302 -3.9983247 ]
3.29579532056 [ 3.5059535   1.99123055 -3.99835547]
3.29489753722 [ 3.50664075  1.99119833 -3.99838599]
3.29401385582 [ 3.50732258  1.99116637 -3.99841627]
3.29314405485 [ 3.50799903  1.99113465 -3.99844632]
3.2922879162

3.24457947017 [ 3.56501481  1.98846175 -4.00097856]
3.24448616016 [ 3.56523637  1.98845136 -4.0009884 ]
3.24439431581 [ 3.56545619  1.98844106 -4.00099816]
3.2443039141 [ 3.56567427  1.98843083 -4.00100785]
3.24421493239 [ 3.56589063  1.98842069 -4.00101746]
3.24412734835 [ 3.56610528  1.98841063 -4.00102699]
3.24404114004 [ 3.56631824  1.98840064 -4.00103645]
3.24395628585 [ 3.56652953  1.98839074 -4.00104583]
3.24387276451 [ 3.56673915  1.98838091 -4.00105514]
3.24379055507 [ 3.56694711  1.98837116 -4.00106438]
3.24370963695 [ 3.56715344  1.98836149 -4.00107354]
3.24362998984 [ 3.56735813  1.98835189 -4.00108263]
3.2435515938 [ 3.56756122  1.98834237 -4.00109165]
3.24347442915 [ 3.5677627   1.98833293 -4.0011006 ]
3.24339847658 [ 3.56796259  1.98832356 -4.00110948]
3.24332371703 [ 3.56816091  1.98831426 -4.00111829]
3.24325013176 [ 3.56835767  1.98830504 -4.00112702]
3.24317770234 [ 3.56855287  1.98829589 -4.00113569]
3.2431064106 [ 3.56874653  1.98828681 -4.00114429]
3.24303623868 [

3.23911072222 [ 3.58519607  1.98751565 -4.00187487]
3.2391033126 [ 3.58525851  1.98751272 -4.00187764]
3.23909601937 [ 3.58532045  1.98750982 -4.00188039]
3.2390888407 [ 3.58538191  1.98750694 -4.00188312]
3.23908177478 [ 3.58544287  1.98750408 -4.00188583]
3.23907481985 [ 3.58550336  1.98750124 -4.00188852]
3.23906797417 [ 3.58556338  1.98749843 -4.00189118]
3.23906123601 [ 3.58562291  1.98749564 -4.00189383]
3.2390546037 [ 3.58568198  1.98749287 -4.00189645]
3.23904807556 [ 3.58574059  1.98749012 -4.00189905]
3.23904164996 [ 3.58579873  1.9874874  -4.00190163]
3.2390353253 [ 3.58585641  1.98748469 -4.0019042 ]
3.23902909998 [ 3.58591364  1.98748201 -4.00190674]
3.23902297244 [ 3.58597042  1.98747935 -4.00190926]
3.23901694115 [ 3.58602675  1.98747671 -4.00191176]
3.2390110046 [ 3.58608263  1.98747409 -4.00191424]
3.23900516129 [ 3.58613808  1.98747149 -4.00191671]
3.23899940977 [ 3.58619308  1.98746891 -4.00191915]
3.23899374859 [ 3.58624766  1.98746635 -4.00192157]
3.23898817634 [ 3

3.23867705426 [ 3.59086533  1.98724988 -4.00212666]
3.23867645648 [ 3.59088306  1.98724904 -4.00212744]
3.2386758681 [ 3.59090065  1.98724822 -4.00212823]
3.23867528895 [ 3.59091811  1.9872474  -4.002129  ]
3.2386747189 [ 3.59093543  1.98724659 -4.00212977]
3.23867415781 [ 3.59095261  1.98724578 -4.00213053]
3.23867360553 [ 3.59096965  1.98724498 -4.00213129]
3.23867306192 [ 3.59098656  1.98724419 -4.00213204]
3.23867252685 [ 3.59100334  1.9872434  -4.00213279]
3.23867200019 [ 3.59101999  1.98724262 -4.00213353]
3.2386714818 [ 3.5910365   1.98724185 -4.00213426]
3.23867097155 [ 3.59105289  1.98724108 -4.00213499]
3.23867046932 [ 3.59106914  1.98724032 -4.00213571]
3.23866997497 [ 3.59108527  1.98723956 -4.00213642]
3.23866948839 [ 3.59110127  1.98723881 -4.00213714]
3.23866900946 [ 3.59111714  1.98723807 -4.00213784]
3.23866853804 [ 3.59113289  1.98723733 -4.00213854]
3.23866807403 [ 3.59114851  1.9872366  -4.00213923]
3.23866761731 [ 3.59116401  1.98723587 -4.00213992]
3.23866716777 [

array([ 3.59153922,  1.98721828, -4.00215659])

In [18]:
from sklearn.linear_model import LinearRegression

In [19]:
lr=LinearRegression()

In [20]:
lr.fit(x.iloc[:,1:],y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [21]:
print(lr.intercept_, lr.coef_)

3.59311441037 [ 1.98714444 -4.00222655]


In [ ]:
wts = [lr.intercept_]
wts.extend(list(lr.coef_))
wts = np.array(wts)
wts

In [ ]:
mycost(y,x,wts)